#编辑环境的默认值
spring:  profiles:    active: prod

#1.使用yml文件有层级结构
#2.使用yml文件key value之间使用冒号连接
#3.赋值时冒号后边必须加空格
--- #环境分割线
spring:  profiles: prod    
server:  port: 8090
  servlet:    context-path: /
 #为user属性赋值 可以编辑中文
user: 
  id: 100
  username: 王者基多拉
  age: 2019
  
--- #环境分割线
spring:
  profiles: dev
    
server:
  port: 8010
  servlet:
    context-path: /jt
    